export const AppStrings = {
  homeAppTitle: "Onde vamos explorar hoje?",
  searchDestinationPlaceholder: "Procurar por destino",
  chooseCategory: "Escolha uma categoria",
  favoritePlaces: "Lugares favoritos",
  popularPackages: "Pacotes populares",
  yourSearch: "Resultados da sua busca",
  basedOnYourPreferences: "Baseado nas suas preferências",
  recomendedPackages: "Pacotes recomendados",
  initDate: "Data de início",
  endDate: "Data de término",
  search: "Procurar",
  selectDate: "Escolha o período da viagem",
  themeDark: "Escuro",
  themeLight: "Claro",
  themeDarkBlue: "Oceano",
  themeSystem: "Tema do sistema",
  errorDefaultNoRefetch:
    "Ocorreu um erro inesperado, tente novamente mais tarde",
  errorDefaultRefetch: "Ocorreu um erro inesperado, tente novamente",
  requiredDateError: "Selecione uma data de início e fim",
  requiredSearchError: "Procure por um destino",
  favoriteText: "Favoritar",
  favoriteBlock: "Faça login para favoritar",
  dreamtrip: "Dreamtrip",
};
